name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: quaiflip
  REGION: us-west4
  ZONE: us-west4-b
  REPOSITORY: quai-flip-build
  IMAGE_NAME: quai-flip-build
  GAR_HOST: us-west4-docker.pkg.dev
  GAR_PATH: us-west4-docker.pkg.dev/quaiflip/quai-flip-build

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.5.1'

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t quai-flip-build:${{ github.sha }} .

      - name: Setup GCloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Docker auth
        run: gcloud auth configure-docker ${{ env.GAR_HOST }} --quiet

      - name: Tag Docker image for Artifact Registry
        run: docker tag ${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.GAR_PATH }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Push Docker image to Artifact Registry
        run: docker push ${{ env.GAR_PATH }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to GCP Compute Engine
        run: |
          gcloud compute ssh instance-1 --zone ${{ env.ZONE }} --command "\
            sudo apt-get update && \
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common && \
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
            sudo add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable' && \
            sudo apt-get update && \
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io && \
            sudo systemctl start docker && \
            gcloud auth print-access-token | sudo docker login -u oauth2accesstoken --password-stdin us-west4-docker.pkg.dev && \
            sudo docker pull ${{ env.GAR_PATH }}/${{ env.IMAGE_NAME }}:${{ github.sha }} && \
            sudo docker stop $(sudo docker ps -q) || true && \
            sudo docker run -d -p 3000:3000 ${{ env.GAR_PATH }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
